webserver:
    enable: true
    address: "0.0.0.0"
    port: "8080"

mail:
    enable: true
    server: "smtp.gmail.com"
    username: "user@gmail.com"
    password: ""
    email: "user@i-401.xyz"
    from: "user@gmail.com"

splunk:
    enable: true
    server: "splunk:8089"
    username: ""
    password: ""
    interval: 500

snmp:
    enable: true
    server: "127.0.0.1"
    community: "my_comm"
    oid: "1.3.6.100.1.2.3.5.1.1.0"

portscan:
    enable: true
    portspec: "~/Repos/nidhogg/portspecs.yml"
    mappings: "~/Repos/nidhogg/mappings.xml"
    timeout: 500

arpscan:
    enable: true
    interface: "eno1"
    db: "/tmp/arp.db"
    timeout: 500
    mac:
      - "00:17:88:28:9f:ca"
      - "00:55:da:50:40:64"
      - "34:7e:5c:31:10:e8"
      - "c8:3c:85:3e:e8:dd"
      - "f4:4d:30:68:9b:d4"
