[package]
name = "splunk"
version = "0.1.0"
authors = ["b401 <sec@i-401.xyz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.101"
curl = "0.4.25"
serde_json = "1.0.41"
serde-xml-rs = "0.3.1"
